### ISSUE TITLE
[Question] Understanding the framebuffer in video_out.h

### ISSUE THREAD

**Issue by marciot** [rossumur/esp_8_bit#39]
Hello,

I am trying to write an ESP32 program that outputs composite video. I tried using bitlumi's work as a starting point, but the colors are highly unstable, at least on my display. Reading through your write up, I can tell your code is superior in this regard, but I am having a bit of difficulty looking at video_out.h and understanding how it works. It looks like `blit` and `burst` are the workhorse of the operation, but they seem to be tied directly to the emulator in use and seem to do some degree of scaling and jiggery pokery depending on the particular emulator.

Ideally, I would like to be able to simplify this so it simply takes a framebuffer of RGB values and paints it. The particular resolution does not matter, but it would be nice if it were either as much as the ESP32 can handle or some fraction of that. Has anyone already done this work of adapting this code into a general purpose graphics library?

Unless you have any other suggestions, I probably will start by finding out what is the highest resolution emulator and try working backwards until I have a way of setting individual pixels.

**Comment by CornN64** [comment]
The emulator does indeed have an 8-bit frame buffer which is possible since these early consoles used a only a handful of colors (63 for NES). So basically the RGB values from these few colors are stored in an indexed array that translate them into YUV color space samples needed for the composite video. Each line from the emulator frame buffer gets converted using a precalculated array of indexed color list to YUV and then send to the DACas samples. To actually do an on the fly calculation from true RGB to YUV is a bit expensive not to mention that a frame buffer with 16 or even 24bits is huge and potentially to big to fit in the ESP32 RAM... 
If you limit yourself to 8bit with RGB mapped as 3-3-2 bits you could still use the same scheme and that would give you 256 colors.

In the emulator each pixel uses only 3 samples out of the 4 available in the translation array in order to get high enough pixel count per line (~305) to fit the 256 pixels from the NES frame buffer while still staying in sync with the color carrier which is why you have these interleave translation of with 12 samples for 4 pixels.

I hope this shed some light on the mechanics for the creation of the composite signal.

**Comment by marciot** [comment]
@CornN64: I have made a lot of progress in adapting the code from the Atari's 336x240 display. I ran into some unexpected hiccups, like the fact doing 8-bit writes to the frame buffer would crash the ESP32. But when I finally learned about IRAM, I was able to modify things to allow me to write colors directly into the frame buffer one byte at a time. It turned out the hue/luminance 8 bit palette used by the Atari was perfect for the color gradients I wanted for my clock project. Here is what the finished project looks like:

![Dali Clock Animation][animation]
[source code]

[animation]: https://github.com/marciot/esp32-dali-clock/raw/master/artwork/animation.gif "Dali Clock Animation"
[source code]: https://github.com/marciot/esp32-dali-clock

Anyhow, the code works pretty amazingly on modern TVs, but I have been having mixed results with a B&W TV. Once in a blue moon I get a decent picture:

![IMG_9666](https://user-images.githubusercontent.com/6752228/137653138-b38fb604-c51d-4345-8631-771ed23007af.JPG)

But more often than not, the vertical hold seems to lock in places other than the start of the frame and I end up with something like this:

![IMG_9697](https://user-images.githubusercontent.com/6752228/137653170-e4829440-8963-4261-9d74-05855f0b5562.JPG)

Out of curiosity, I took a look at the signal on my scope and although I can pick out the sync, color burst and front porch, it's definitely a bit soft:

![IMG_9688](https://user-images.githubusercontent.com/6752228/137653611-ca11b70b-fc12-478d-bd7d-5b86f988bbda.JPG)

By comparison, the signal from an Atari Flashback 2 (the only other NTSC device I have) looks pretty sharp:

![IMG_9691](https://user-images.githubusercontent.com/6752228/137653448-f36b36cc-dfaf-4656-9b1b-36598875d694.JPG)

I don't exactly think anything can be done about this from a coding perspective. My understanding is that DAC on the ESP32 is meant to operate at audio frequencies, so I bet it really is struggling to operate in the megahertz range and my little TV probably isn't very good at making up the difference!

**Comment by marciot** [comment]
@CornN64: Anyhow, if you don't mind helping the understand some bit and pieces about the code:

```
    void IRAM_ATTR burst_ntsc(uint16_t* line)
    {
        int i,phase;
        ...
        // 4 samples per color clock
        for (i = _hsync; i < _hsync + (4*10); i += 4) {
            line[i+1] = BLANKING_LEVEL;
            line[i+0] = BLANKING_LEVEL + BLANKING_LEVEL/2;
            line[i+3] = BLANKING_LEVEL;
            line[i+2] = BLANKING_LEVEL - BLANKING_LEVEL/2;
       }
       ...
    }
```

I understand this is writing 16-bit values to the line buffer and in particular, writing a saw-tooth wave as an approximation to the colorburst. What I do not understand, however, is why the samples are written in the order `line[i+1]`, `line[i+0]`, `line[i+3]`, `line[i+2]`. What exactly is the reason for writing the samples in such a peculiar order?

I am also way confused by this function:

```
// draw a line of game in NTSC
    void IRAM_ATTR blit_ntsc(uint8_t* src, uint16_t* dst)
    {
        uint32_t* d = (uint32_t*)dst;
        const uint32_t* p = _palette;
        uint32_t c;
        int i;

        // 2 pixels per color clock, 4 samples per cc, used by atari
        // AA AA
        // 192 color clocks wide
        // only show 336 pixels
        d += 16;
        for (i = 0; i < 336; i += 4) {
            uint32_t c = *((uint32_t*)src); // screen may be in 32 bit mem
            d[0] = p[(uint8_t)c];
            d[1] = p[(uint8_t)(c>>8)] << 8;
            d[2] = p[(uint8_t)(c>>16)];
            d[3] = p[(uint8_t)(c>>24)] << 8;
            d += 4;
            src += 4;
        }
        END_TIMING();
    }
```

I see that it is reading four color values at a time as 32-bit words, so there is a bit of bit shifting going on to extract the bytes. I suppose this could have been done with 8-bit reads for clarity, but maybe this is more performant. Moving on, if I rewrite it like this, it gets me to my question:

```
// draw a line of game in NTSC
    void IRAM_ATTR blit_ntsc(uint8_t* src, uint16_t* dst)
    {
        uint32_t* d = (uint32_t*)dst;
        const uint32_t* p = _palette;
        uint32_t c;
        int i;

        // 2 pixels per color clock, 4 samples per cc, used by atari
        // AA AA
        // 192 color clocks wide
        // only show 336 pixels
        d += 16;
        for (i = 0; i < 336; i += 4) {
            uint32_t c = *((uint32_t*)src); // screen may be in 32 bit mem
            uint8_t c1 = c;
            uint8_t c2 = c>>8;
            uint8_t c3 = c>>16;
            uint8_t c4 = c >> 24;
            d[0] = p[c1];
            d[1] = p[c2] << 8;
            d[2] = p[c3];
            d[3] = p[c4] << 8;
            d += 4;
            src += 4;
        }
        END_TIMING();
    }
```


My assumption is that `p` is an array of bit patterns that must be loaded up into the sample buffer to write the appropriate color, but some things don't make sense.

Focusing on these lines:

```
   d[0] = p[c1];
   d[1] = p[c2] << 8;
   d[2] = p[c3];
   d[3] = p[c4] << 8;
```

1) Why are the entries in the `p` table 32 bits, while this function is copying the values into a 16-bit sample?
2) Why is every other sample shifted by 8-bits?

As far as I can tell, this means that for the even numbered pixels, the two least significant bytes are copied from the table; for the odd numbered pixels, only the second and third bytes are copied. In all cases, the fourth byte, most significant byte, seems to be ignored. Why is this?
