### ISSUE TITLE
SNES CONTROLLER SUPPORT 

### ISSUE THREAD

**Issue by udayanga87** [rossumur/esp_8_bit#7]
Is there anyway to add old SNES controller support for this?

**Comment by llamitaiot** [comment]
I was thinking the same thing. I want to grab both a nes and Sega controllers and put an Arduino with Bluetooth inside (or maybe just another esp32) to use them as controllers.

**Comment by udayanga87** [comment]
@cornN64 added support for nes and snes controllers. Tested and it’s working.
https://github.com/rossumur/esp_8_bit/pull/16
